services:
    web:
        image: catalogue:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        restart: unless-stopped
    nginx:
        restart: unless-stopped
        container_name: nginx
        image: nginx
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
        depends_on:
        - web
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email ukiras@gmail.com -d test.kirangautam.com --agree-tos

